
(
Quarks.install("https://github.com/scztt/SZPat.quark");
Quarks.install("https://github.com/scztt/BandSplitter.quark");
Quarks.install("https://github.com/scztt/Require.quark");
Quarks.install("https://github.com/scztt/ServerView.quark");
Quarks.install("https://github.com/scztt/Connection.quark");
Quarks.install("https://github.com/scztt/LanguageServer.quark");
)

QuarkEditor.open("/Users/chrysanth/Desktop/Scztt-Core-Quarks/PatternToolkit")