
(
Quarks.install("https://github.com/scztt/SZPat.quark");
Quarks.install("https://github.com/scztt/BandSplitter.quark");
Quarks.install("https://github.com/scztt/Require.quark");
Quarks.install("https://github.com/scztt/ServerView.quark");
Quarks.install("https://github.com/scztt/Connection.quark");
Quarks.install("https://github.com/scztt/LanguageServer.quark");
)

(

Quarks.install("/Volumes/chrys-rescue/WorkshopSupplies/quarks")
)