
(
Quarks.install("https://github.com/scztt/SZPat.quark");
Quarks.install("https://github.com/scztt/BandSplitter.quark");
Quarks.install("https://github.com/scztt/Require.quark");
Quarks.install("https://github.com/scztt/ServerView.quark");
Quarks.install("https://github.com/scztt/Connection.quark");
Quarks.install("https://github.com/scztt/LanguageServer.quark");
)

(

Quarks.install("/Volumes/chrys-rescue/WorkshopSupplies/quarks")
)

// 1. Download SuperCollider:
//    https://supercollider.github.io/
// 2. Download sc3-plugins
//    https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.13.0
// 3. Install sc3-plugins
//    ~/Library/Application Support/SuperCollider
// 4. Download workshop materials
//    https://github.com/scztt/BROMPTON-WORKSHOP/releases/tag/Nov-22-2025
//.   both Source Code and Workshop materials
